### ISSUE TITLE
Question: body_add_vg is defunct

### ISSUE THREAD

**Issue by cvanderaa** [davidgohel/rvg#36]
Hello, 

I just realized that `body_add_vg` is now defunct. Is there an alternative function to add a plot as a vectorized object to a document (Word or PPT) with `rvg`? The error message suggests to use  `officer::body_add_img`, but as far as I understand this adds plots to a document as plain images, not vectorized objects.

Thanks in advance!

**Comment by davidgohel** [comment]
Hello,

Yes, it was deprecated for 2 years. The feature still exists for pptx and xlsx (and there is no plan to remove them) but not for docx. 

You could use `emf` function as an alternative (not editable but vector graphic)

#' @note
#' The function is maintained but using it
#' should be avoided: Word text boxes, the elements used to put text in a graphic,
#' are adding extra space on top and bottom of the shape. As there is no clear rule
#' available to handle that, it makes impossible to compute what should be the
#' exact position of a text. This can affect the whole rendering of the graphic.
#'
#' The function should then be considered as a failed experience. An
#' alternative is to use EMF format, this will not allow editing the graphic but
#' the display is made as vector graphic.

Thanks for the question, I made me realized I forgot to update the officer page about it. 
It shows an example on how to use `emf`:

https://davidgohel.github.io/officer/articles/offcran/graphics.html#r-plots-1

Also, not now, but I will try to add svg also in the supported format, see 

https://github.com/davidgohel/officer/issues/297

**Comment by cvanderaa** [comment]
Hello David, 

Thanks a lot for your answer ! This helps a lot !

**Comment by Lukas-1** [comment]
In my experience, the rendering of output from devEMF::emf in Word is not ideal, for example, the characters in the text look quite thin. Even when I save the document as a PDF, I'm not entirely happy with the kerning.

I've achieved better results by first placing figures into a PowerPoint file, choosing save as .emf, and then inserting that into Word. However, that seems to make the resulting .emf file incompatible with Google Docs and other non-Office programs. Inserting .svg files (produced from .pdf files using Inkscape) into Word also works, but it really inflates the file size, because Word apparently creates a .PNG version of each .svg file for the sake of backwards compatibility with older versions of Word.

Based on what I see with PowerPoint, producing graphs using DrawingML gives the smallest file sizes, the best rendering, and is even quite fast to produce. So if this were possible for Word as well, it would be amazing.

I am not really looking for a way to insert graphics into Word documents, I prefer to do that manually. Ideally, the R function would automatically generate a document of sufficient size to contain my graph, and place a graph of some specified height and width in inches in the middle of that document. I'd copy the graph and paste it into my target document.

Is there any chance that this may be possible in the future?
