### ISSUE TITLE
Misaligned text in PowerPoint / RStudio Server

### ISSUE THREAD

**Issue by pteridin** [davidgohel/rvg#45]
ggplot2 text fields exported into PowerPoint in RStudio server are misaligned. 
![image](https://user-images.githubusercontent.com/29350560/177952021-ae35ad45-7cf1-4f8c-aab1-2292e08a395b.png)
This does not happen in a local RStudio installation.

Text is fixed when manually applying "right click" > "format shape..."  > "text options" > "whatever that option may be called"
![image](https://user-images.githubusercontent.com/29350560/177954333-c50056b3-3c96-4d97-b87b-62b09c4d73e3.png)

Would suggest making that format option the default for every text exported into PowerPoint documents via RVG. This would also makes it much easier to edit text after export into pptx files.

**Comment by davidgohel** [comment]
Could you provide a reproducible example? (use reprex if possible with session info details)

I suspect you did not pay attention to the font you are using on the Server and if the font is available on the computer. This because a linux server often comes with only one single font.

See first paragraphs here: https://davidgohel.github.io/rvg/articles/offcran/customizing.html

**Comment by pteridin** [comment]
Ah, okay. Spacing and position is calculated based on font - when the font is not available on Windows or on the Server (Linux) the alignment is off? Then I would suggest that you are ideed right. Will test it probably next week.

Thank you so much for these great packages and the support!

**Comment by pteridin** [comment]
**Fixed** 
Installing the fonts fixed the problem. See the description of @davidgohel
